function W0_1 = W0_1_mat
%W0_1_MAT
%    W0_1 = W0_1_MAT

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:10:19

W0_1 = [0.0;0.0;0.0;0.0;0.0;0.0];
