function W1_1 = W1_1_mat
%W1_1_MAT
%    W1_1 = W1_1_MAT

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:10:38

W1_1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,3]);
