function out1 = W2_1_mat
%W2_1_MAT
%    OUT1 = W2_1_MAT

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Jan-2022 21:31:05

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
