function W12 = W2_2_mat(q2,q1dot,q2dot)
%W2_2_MAT
%    W12 = W2_2_MAT(Q2,Q1DOT,Q2DOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Jan-2022 21:31:05

t2 = cos(q2);
t3 = sin(q2);
t4 = q1dot.^2;
t5 = t2.*t3.*t4;
W12 = reshape([0.0,t5,0.0,0.0,0.0,0.0,0.0,-q1dot.*q2dot.*t2,0.0,0.0,0.0,0.0,0.0,t4.*cos(q2.*2.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-q1dot.*q2dot.*t3,0.0,0.0,0.0,0.0,0.0,-t5,0.0,0.0,0.0,0.0],[6,6]);
