function W13 = W2_3_mat(q2,q3,q1dot,q2dot,q3dot)
%W2_3_MAT
%    W13 = W2_3_MAT(Q2,Q3,Q1DOT,Q2DOT,Q3DOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Jan-2022 21:31:05

t2 = q2+q3;
t3 = q2dot+q3dot;
t4 = q2.*2.0;
t5 = q3.*2.0;
t6 = q1dot.^2;
t7 = cos(t2);
t8 = sin(t2);
t9 = t2.*2.0;
t10 = cos(t9);
t11 = sin(t9);
t12 = q1dot.*t3.*t7;
t13 = q1dot.*t3.*t8;
t14 = -t12;
t15 = -t13;
t16 = t6.*t10;
t17 = (t6.*t11)./2.0;
t18 = -t17;
W13 = reshape([0.0,t17,t17,0.0,0.0,0.0,0.0,t14,t14,0.0,0.0,0.0,0.0,t16,t16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15,t15,0.0,0.0,0.0,0.0,t18,t18,0.0,0.0,0.0],[6,6]);
