function W14 = W2_4_mat(q2,q3,q4,q1dot,q2dot,q3dot,q4dot)
%W2_4_MAT
%    W14 = W2_4_MAT(Q2,Q3,Q4,Q1DOT,Q2DOT,Q3DOT,Q4DOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Jan-2022 21:31:06

t2 = q2.*2.0;
t3 = q3.*2.0;
t4 = q4.*2.0;
t5 = q1dot.^2;
t6 = q2+q3+q4;
t7 = q2dot+q3dot+q4dot;
t8 = cos(t6);
t9 = sin(t6);
t10 = t2+t3+t4;
t11 = cos(t10);
t12 = sin(t10);
t13 = q1dot.*t7.*t8;
t14 = q1dot.*t7.*t9;
t15 = -t13;
t16 = -t14;
t17 = t5.*t11;
t18 = (t5.*t12)./2.0;
t19 = -t18;
W14 = reshape([0.0,t18,t18,t18,0.0,0.0,0.0,t15,t15,t15,0.0,0.0,0.0,t17,t17,t17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t16,t16,t16,0.0,0.0,0.0,t19,t19,t19,0.0,0.0],[6,6]);
