function X0_1 = X0_1_mat
%X0_1_MAT
%    X0_1 = X0_1_MAT

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:10:03

X0_1 = [0.0;0.0;0.0;0.0;0.0;0.0];
