function X0_4 = X0_4_mat(q1,q2,q3,q1rdot,q2rdot,q3rdot)
%X0_4_MAT
%    X0_4 = X0_4_MAT(Q1,Q2,Q3,Q1RDOT,Q2RDOT,Q3RDOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:10:04

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t2.^2;
t9 = t5.^2;
t10 = t6.*(1.7e+1./4.0e+1);
t11 = t2.*t3.*(1.7e+1./4.0e+1);
t12 = t3.*t5.*(1.7e+1./4.0e+1);
t14 = t2.*1.0915e-1;
t15 = t5.*1.0915e-1;
t16 = t3.*t7.*3.9225e-1;
t17 = t4.*t6.*3.9225e-1;
t18 = t5.*t6.*t7.*3.9225e-1;
t19 = t2.*t3.*t4.*3.9225e-1;
t20 = t3.*t4.*t5.*3.9225e-1;
t21 = t2.*t6.*t7.*3.9225e-1;
t13 = -t11;
t22 = -t18;
t23 = -t19;
t24 = t16+t17;
t25 = t24.^2;
t26 = t10+t24;
t28 = t15+t21+t23;
t29 = t14+t20+t22;
t27 = t26.^2;
t30 = t2.*t28;
t31 = t5.*t29;
t33 = t12+t29;
t34 = t13+t28;
t38 = t9.*t24.*t26;
t39 = t8.*t24.*t26;
t32 = -t31;
t35 = t5.*t33;
t36 = t2.*t34;
t40 = t2.*t24.*t33;
t41 = t5.*t24.*t34;
t42 = t2.*t26.*t33;
t43 = t5.*t26.*t34;
t37 = -t35;
t44 = t30+t32;
t46 = t40+t41;
t47 = t42+t43;
t45 = t36+t37;
t48 = -t44.*(t35-t36);
t49 = t38+t39+t48;
X0_4 = [-q2rdot.*t47-q3rdot.*t46+q1rdot.*(t33.^2+t34.^2);-q1rdot.*t47+q3rdot.*t49+q2rdot.*((t35-t36).^2+t8.*t27+t9.*t27);-q1rdot.*t46+q2rdot.*t49+q3rdot.*(t8.*t25+t9.*t25+t44.^2);0.0;0.0;0.0];
