function X1_1 = X1_1_mat
%X1_1_MAT
%    X1_1 = X1_1_MAT

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:10:06

X1_1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,3]);
