function X1_2 = X1_2_mat(q1,q2,q1rdot,q2rdot)
%X1_2_MAT
%    X1_2 = X1_2_MAT(Q1,Q2,Q1RDOT,Q2RDOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:10:07

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.^2;
t7 = t4.^2;
t8 = q1rdot.*t2.*t3.*(1.7e+1./2.0e+1);
t9 = q1rdot.*t2.*t3.*(1.7e+1./4.0e+1);
t10 = q1rdot.*t3.*t4.*(1.7e+1./2.0e+1);
t11 = q1rdot.*t2.*t5.*(1.7e+1./4.0e+1);
t12 = q1rdot.*t3.*t4.*(1.7e+1./4.0e+1);
t13 = q2rdot.*t2.*t5.*(1.7e+1./4.0e+1);
t14 = q1rdot.*t4.*t5.*(1.7e+1./4.0e+1);
t15 = q2rdot.*t4.*t5.*(1.7e+1./4.0e+1);
t16 = t3.*t6.*(1.7e+1./4.0e+1);
t17 = t3.*t7.*(1.7e+1./4.0e+1);
t18 = -t13;
t19 = q2rdot.*t5.*t6.*(1.7e+1./4.0e+1);
t20 = q2rdot.*t5.*t7.*(1.7e+1./4.0e+1);
t21 = t8+t15;
t22 = t9+t15;
t23 = t10+t18;
t24 = t12+t18;
t25 = t16+t17;
t26 = t4.*t22;
t27 = t2.*t24;
t29 = q2rdot.*t2.*t25.*2.0;
t30 = q2rdot.*t4.*t25.*2.0;
t28 = -t27;
t31 = -t30;
t32 = t14+t29;
t33 = t11+t31;
t34 = t19+t20+t26+t28;
X1_2 = reshape([-t2.*t3.*t21-t3.*t4.*t23,-t5.*t34-t2.*t3.*t32+t3.*t4.*t33,0.0,0.0,0.0,0.0,-t2.*t23+t4.*t21,t2.*t33+t4.*t32,0.0,0.0,0.0,0.0,-t2.*t5.*t21-t4.*t5.*t23,t3.*t34-t2.*t5.*t32+t4.*t5.*t33,0.0,0.0,0.0,0.0],[6,3]);
