function X2_1 = X2_1_mat(q1rdot)
%X2_1_MAT
%    X2_1 = X2_1_MAT(Q1RDOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:10:15

X2_1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,q1rdot,0.0,0.0,0.0,0.0,0.0],[6,6]);
