function X2_2 = X2_2_mat(q1,q2,q1rdot,q2rdot)
%X2_2_MAT
%    X2_2 = X2_2_MAT(Q1,Q2,Q1RDOT,Q2RDOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:10:15

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.^2;
t7 = t4.^2;
t8 = t6+t7;
X2_2 = reshape([-q2rdot.*t4.*t5,0.0,0.0,0.0,0.0,0.0,-q2rdot.*t2.*t5,q2rdot.*t4.*t8,0.0,0.0,0.0,0.0,q1rdot.*t5-q2rdot.*t3.*t4,0.0,0.0,0.0,0.0,0.0,0.0,q2rdot.*t2.*t8,0.0,0.0,0.0,0.0,q2rdot.*t2.*t3,q1rdot.*t8,0.0,0.0,0.0,0.0,q1rdot.*t3,0.0,0.0,0.0,0.0,0.0],[6,6]);
