function Z0_1 = Z0_1_mat
%Z0_1_MAT
%    Z0_1 = Z0_1_MAT

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:12:23

Z0_1 = [0.0;0.0;0.0;0.0;0.0;0.0];
