function Z0_2 = Z0_2_mat(q1,q2)
%Z0_2_MAT
%    Z0_2 = Z0_2_MAT(Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:12:23

t2 = cos(q2);
Z0_2 = [0.0;t2.*cos(q1).^2.*(-4.16925)-t2.*sin(q1).^2.*4.16925;0.0;0.0;0.0;0.0];
