function Z1_1 = Z1_1_mat
%Z1_1_MAT
%    Z1_1 = Z1_1_MAT

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:12:23

Z1_1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,3]);
