function Z1_2 = Z1_2_mat(q2)
%Z1_2_MAT
%    Z1_2 = Z1_2_MAT(Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:12:23

Z1_2 = reshape([0.0,cos(q2).*(-9.81e+2./1.0e+2),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sin(q2).*(-9.81e+2./1.0e+2),0.0,0.0,0.0,0.0],[6,3]);
