function Z1_3 = Z1_3_mat(q2,q3)
%Z1_3_MAT
%    Z1_3 = Z1_3_MAT(Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:12:24

t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
t6 = t2.*t3.*(9.81e+2./1.0e+2);
t7 = t2.*t5.*(9.81e+2./1.0e+2);
t8 = t3.*t4.*(9.81e+2./1.0e+2);
t9 = t4.*t5.*(9.81e+2./1.0e+2);
t10 = -t6;
t11 = -t7;
t12 = -t8;
t13 = t9+t10;
t14 = t11+t12;
Z1_3 = reshape([0.0,t13,t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t14,t14,0.0,0.0,0.0],[6,3]);
