function Z1_4 = Z1_4_mat(q2,q3,q4)
%Z1_4_MAT
%    Z1_4 = Z1_4_MAT(Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:12:24

t2 = cos(q2);
t3 = cos(q3);
t4 = cos(q4);
t5 = sin(q2);
t6 = sin(q3);
t7 = sin(q4);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t9+t10;
t14 = t8+t12;
t15 = t4.*t13.*(9.81e+2./1.0e+2);
t16 = t7.*t13.*(9.81e+2./1.0e+2);
t17 = -t15;
t18 = t4.*t14.*(9.81e+2./1.0e+2);
t19 = t7.*t14.*(9.81e+2./1.0e+2);
t20 = -t18;
t21 = -t19;
t22 = t16+t20;
t23 = t17+t21;
Z1_4 = reshape([0.0,t22,t22,t22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t23,t23,t23,0.0,0.0],[6,3]);
