function Z1_5 = Z1_5_mat(q2,q3,q4,q5)
%Z1_5_MAT
%    Z1_5 = Z1_5_MAT(Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Feb-2022 19:12:24

t2 = cos(q2);
t3 = cos(q3);
t4 = cos(q4);
t5 = cos(q5);
t6 = sin(q2);
t7 = sin(q3);
t8 = sin(q4);
t9 = sin(q5);
t10 = t2.*t3;
t11 = t2.*t7;
t12 = t3.*t6;
t13 = t6.*t7;
t14 = -t13;
t15 = t11+t12;
t16 = t10+t14;
t17 = t4.*t15;
t18 = t8.*t15;
t19 = t4.*t16;
t20 = t8.*t16;
t21 = -t18;
t22 = t17.*(9.81e+2./1.0e+2);
t23 = -t22;
t24 = t20.*(9.81e+2./1.0e+2);
t26 = t17+t20;
t27 = t19+t21;
t28 = t5.*(t18-t19).*(-9.81e+2./1.0e+2);
t29 = t9.*(t18-t19).*(-9.81e+2./1.0e+2);
t30 = t5.*(t18-t19).*(9.81e+2./1.0e+2);
t25 = -t24;
t31 = t23+t25;
Z1_5 = reshape([0.0,t30,t30,t30,t9.*t26.*(9.81e+2./1.0e+2),0.0,0.0,t29,t29,t29,t5.*t26.*(9.81e+2./1.0e+2),0.0,0.0,t31,t31,t31,0.0,0.0],[6,3]);
